version: "3.8"

services:
  db:
    container_name: info_pmnh_db
    image: postgres:14-alpine
    restart: always
    user: postgres  # importante definir o usuário
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres  # senha padrão
      - POSTGRES_USER=postgres  # usuário padrão
      - POSTGRES_DB=info_pmnh_db  # necessário porque foi configurado assim no settings
    ports:
      - 5433:5432  # repare na porta externa 5433
    networks:
      - info_pmnh_network

  pgadmin:
    container_name: info_pmnh_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
       - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5051:80
    networks:
      - info_pmnh_network


#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: info_pmnh_app
#    hostname: app
#    stdin_open: true
#    expose:
#      - '8000'
#    volumes:
#      - .env.docker:/app/.env
#    command: bash -c "gunicorn backend.wsgi:application -b 0.0.0.0:8000"
#    depends_on:
#      - db
#    networks:
#      - info_pmnh_network

#  nginx:
#    container_name: info_pmnh_nginx
#    image: nginx
#    hostname: nginx
#    ports:
#      - '80:8000'
#    volumes:
#      - ./docker/config/nginx/:/etc/nginx/conf.d/
#    depends_on:
#      - app
#    networks:
#      - info_pmnh_network

volumes:
  pgdata:  # mesmo nome do volume externo definido na linha 10
  pgadmin:

networks:
  info_pmnh_network: