# Generated by Django 4.1.7 on 2023-02-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('diretoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setores.diretoria')),
            ],
        ),
    ]
